artifact_location: file:///home/lishuonewbing/agent测试/artifacts/qlib_runs/qlib_us_core_daily_2020_2025/mlruns_debug/731223021178137045
creation_time: 1778475938434
experiment_id: '731223021178137045'
last_update_time: 1778475938434
lifecycle_stage: active
name: debug
trace_location: null
workspace: default
