artifact_uri: file:///home/lishuonewbing/agent测试/artifacts/qlib_runs/qlib_us_core_daily_2020_2025/mlruns_debug/731223021178137045/dc8706d0213947e59dbe1ccdac4c4dff/artifacts
deleted_time: null
end_time: null
entry_point_name: ''
experiment_id: '731223021178137045'
lifecycle_stage: active
run_id: dc8706d0213947e59dbe1ccdac4c4dff
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1778475939068
status: 1
tags: []
user_id: lishuonewbing
