artifact_location: file:///home/lishuonewbing/agent测试/artifacts/qlib_runs/qlib_us_core_daily_2020_2025/mlruns_debug/0
creation_time: 1778475938420
experiment_id: '0'
last_update_time: 1778475938420
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
